// <auto-generated />
using PlaneWeb.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PlaneWeb.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PlaneWebDbContext))]
    [Migration("20261003212900_MapSettings")]
    partial class MapSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PlaneWeb.Core.WallSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CenterLat")
                        .HasColumnType("REAL");

                    b.Property<double>("CenterLon")
                        .HasColumnType("REAL");

                    b.Property<bool>("IncludeGround")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeHelicopters")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeLight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapLayer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("MapShowAll")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAltitudeFt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAreaFlights")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinAltitudeFt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolygonJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RadiusNm")
                        .HasColumnType("REAL");

                    b.Property<int>("RotateSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shape")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TraceBackfill")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackedFlights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrailMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Units")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
